"""Assemble everything in results/ into docs/RESULTS.md.

Nothing here computes: it reads the manifests each step wrote and lays them out in
build order, so the report cannot drift from the runs that produced it.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime

from src.config import RESULTS, ROOT

DOCS = ROOT / "docs"


def _load_one(pattern: str) -> dict | None:
    """Per-dataset artefacts are scoped by source and split, so the report picks the
    real-data run over a synthetic one when both are present."""
    paths = sorted(RESULTS.glob(f"{pattern}.json"))
    if not paths:
        return None
    real = [p for p in paths if "synthetic" not in p.name]
    return json.loads((real or paths)[0].read_text())


def _load(name: str) -> dict | None:
    path = RESULTS / f"{name}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def _fmt(x, digits: int | None = None) -> str:
    """Scale the precision to the magnitude: a branching ratio needs four decimals,
    a total xG of 957 does not."""
    if x is None:
        return "--"
    if isinstance(x, bool):
        return "yes" if x else "no"
    if isinstance(x, float):
        if digits is not None:
            return f"{x:.{digits}f}"
        a = abs(x)
        if a >= 100:
            return f"{x:,.1f}"
        if a >= 1:
            return f"{x:.2f}"
        return f"{x:.4f}"
    return str(x)


def _table(rows: list[dict], columns: list[str]) -> str:
    head = "| " + " | ".join(columns) + " |"
    rule = "| " + " | ".join("---" for _ in columns) + " |"
    body = ["| " + " | ".join(_fmt(r.get(c)) for c in columns) + " |" for r in rows]
    return "\n".join([head, rule, *body])


def build() -> str:
    out: list[str] = []
    add = out.append

    add("# Results\n")
    add(
        "Generated by `make report` from the manifests in `results/`. Every number "
        "below is read from the run that produced it; nothing here is recomputed.\n"
    )
    add(f"_Assembled {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}._\n")

    # ---- step 1
    add("\n## 1. Data\n")
    # Synthetic runs are the smoke test for the pipeline, not a result. They are listed
    # only when there is no real data to report, so the report never quietly presents a
    # demo as a finding.
    real_present = any(
        (RESULTS / f"build_{s}.json").exists() for s in ("understat", "statsbomb", "wyscout", "pooled")
    )
    for source in ("pooled", "statsbomb", "wyscout", "understat", "synthetic"):
        if source == "synthetic" and real_present:
            continue
        man = _load(f"build_{source}")
        if not man:
            continue
        p = man["payload"]
        add(
            f"**{source}** -- {p['matches']} matches, {p['events']} shots "
            f"({p['events_per_match_mean']:.1f} per match), seasons {p['seasons']}, "
            f"red cards {'available' if p['red_cards_known'] else 'NOT available'}.\n"
        )
        add(f"Situations: {p['situations']}. Goals: {p['goals']}. Mean xG {p['mean_xg']:.3f}.\n")
        st = p.get("strata")
        if st:
            add(
                f"Strata: by provider {st['matches_by_source']}, by gender {st['matches_by_gender']}, "
                f"one-club league-seasons {st['one_club_matches']} matches.\n"
            )

    # ---- step 2
    cals = sorted(RESULTS.glob("dedup_calibration_*.json"))
    if cals:
        add("\n## 2. De-duplication threshold\n")
        add(
            "Calibrated per provider on its own second clock: how a rebound gets logged is a "
            "property of the provider, not of football.\n"
        )
        rows = []
        note = None
        for path in cals:
            p = json.loads(path.read_text())["payload"]
            a = p["applied_with_configured_threshold"]
            rows.append(
                {
                    "provider": p["source"],
                    "matches": p["matches"],
                    "excess dies at (s)": f"{p['threshold_seconds']:.0f}",
                    "excess mass": f"{p['excess_mass_below_threshold']:.1%}",
                    "applied at (s)": f"{p['configured_threshold_seconds']:.0f}",
                    "shots removed": f"{a['removed_fraction']:.1%}",
                    "longest run": a["max_run_length"],
                }
            )
            note = p["note"]
        add(
            _table(
                rows,
                [
                    "provider",
                    "matches",
                    "excess dies at (s)",
                    "excess mass",
                    "applied at (s)",
                    "shots removed",
                    "longest run",
                ],
            )
        )
        add("The guard rejects any rule that removes more than 15% of shots.\n")
        if note:
            add(f"\n> {note}\n")

    # ---- step 3
    for key in sorted(RESULTS.glob("null_*.json")):
        if "synthetic" in key.name and real_present:
            continue
        man = json.loads(key.read_text())
        p = man["payload"]
        bg, ks = p["background"], p["time_rescaling"]
        add(f"\n## 3. Null model ({key.stem.replace('null_', '')})\n")
        rows = [{"term": "home advantage", "estimate": bg["theta_home"]}]
        for label, block in (("score differential", bg.get("g_score")), ("man advantage", bg.get("h_red"))):
            for k, v in (block or {}).items():
                rows.append({"term": f"{label} {k}", "estimate": v})
        add(_table(rows, ["term", "estimate"]))
        if bg.get("dropped_terms"):
            add("\nDropped as inestimable on this slate: " + "; ".join(bg["dropped_terms"]) + ".\n")
        add(
            f"\nTime rescaling on {ks['n']} gaps: KS statistic {ks['ks_stat']:.4f}. "
            f"Per team-process, {ks['frac_reject_05']:.1%} reject at alpha = 0.05 "
            f"(nominal is 5%), and those p-values are uniform "
            f"(KS p = {ks['uniformity_ks_pvalue']:.3f}).\n"
        )

    # ---- estimator choice
    man = _load_one("estimator_comparison_*")
    if man:
        add(f"\n## 4. Which estimator -- {man['name'].replace('estimator_comparison_', '')}\n")
        rows = man["payload"]["summary"]
        add(_table(rows, ["method", "eta_star", "mean_eta_hat", "bias", "mean_tau"]))
        add(
            "\nThe two-stage fit docs/math.md sketches gives back about a third of a planted "
            "branching ratio. Fitting a Poisson background to data that contains excitation "
            "inflates mu by roughly 1/(1 - rho); freezing that inflated mu leaves nothing for "
            "eta. The joint fit is the default for this reason.\n"
        )

    # ---- step 5
    man = _load_one("recovery_*")
    if man:
        add(f"\n## 5. Recovery test (the gate) -- {man['name'].replace('recovery_', '')}\n")
        for method, r in man["payload"]["results"].items():
            add(
                f"**{method}**: planted eta_self = {r['eta_planted']}, recovered "
                f"{r['mean_eta_hat_self']:.4f} (sd {r['sd_eta_hat_self']:.4f}, "
                f"bias {r['bias']:+.4f}) over {r['n_replicates']} replicates; "
                f"tau planted {r['tau_planted_minutes']:.1f} min, recovered "
                f"{r['mean_tau_hat']:.2f} min. **{'PASS' if r['passed'] else 'FAIL'}**\n"
            )

    # ---- step 6
    man = _load_one("power_*")
    if man:
        p = man["payload"]
        add(f"\n## 6. Detection floor -- {man['name'].replace('power_', '')}\n")
        add(_table(p["curve"], ["eta_star", "n_replicates", "power", "mean_eta_hat", "bias", "sd_eta_hat"]))
        add(
            f"\nCritical value {p['critical_value']:.4f} (the {1 - p['alpha']:.0%} quantile of the "
            f"eta* = 0 arm). **Detection floor = {_fmt(p['detection_floor'], 3)}** at "
            f"{p['target_power']:.0%} power; linear read-off between grid points "
            f"{_fmt(p['detection_floor_interpolated'], 3)}.\n"
        )
        add(
            "The `bias` column is a result in its own right: it is how much of a real effect the "
            "background model absorbs.\n"
        )
        add(
            "\nThe `power` figure on the `eta_star = 0` row is the level the critical value was "
            "*set* to, not an independent estimate of it: that arm defines the threshold, so it "
            "hits alpha by construction. Every other row is a real rejection rate against it.\n"
        )

    # ---- the floors, side by side: this is the decision-relevant comparison
    floors = sorted(RESULTS.glob("power_*.json"))
    floors = [f for f in floors if "synthetic" not in f.name]
    if len(floors) > 1:
        add("\n## 6b. What the clock costs: detection floors side by side\n")
        payloads = {f.stem.replace("power_", ""): json.loads(f.read_text())["payload"] for f in floors}
        grid = sorted({r["eta_star"] for p in payloads.values() for r in p["curve"]})
        rows = []
        for eta in grid:
            row = {"planted eta_self": eta}
            for name, pl in payloads.items():
                hit = next((r for r in pl["curve"] if r["eta_star"] == eta), None)
                clock = "minute" if pl.get("minute_clock") else "second"
                row[f"{name} ({clock}) eta_hat"] = hit["mean_eta_hat"] if hit else None
                row[f"{name} power"] = hit["power"] if hit else None
            rows.append(row)
        add(_table(rows, list(rows[0])))
        add("")
        for name, pl in payloads.items():
            add(
                f"- **{name}** ({'minute' if pl.get('minute_clock') else 'second'} clock): "
                f"floor {_fmt(pl['detection_floor'], 2)}, interpolated "
                f"{_fmt(pl['detection_floor_interpolated'], 3)}\n"
            )
        add(
            "\nA floor that moves with the clock rather than with the sample size is not a "
            "precision problem. Below the point where the minute-clock estimator breaks through, "
            "it does not return a small noisy number -- it returns zero, because the same-minute "
            "collapse has removed the pairs that carry the excitation. More matches do not lower "
            "that floor.\n"
        )

    # ---- step 7
    man = _load_one("rounding_bias_*")
    if man:
        p = man["payload"]
        sr, mr = p["second_resolution"], p["minute_resolution"]
        add("\n## 7. Rounding bias\n")
        add(f"The same {p['matches']} matches, fitted twice.\n")
        add(
            _table(
                [
                    {
                        "resolution": "second (StatsBomb clock)",
                        "eta_self": sr["eta_self"],
                        "eta_cross": sr["eta_cross"],
                        "tau_min": sr["tau_minutes"],
                        "events after dedup": sr["dedup"]["n_after"],
                    },
                    {
                        "resolution": "integer minute (Understat clock)",
                        "eta_self": mr["eta_self_mean"],
                        "eta_cross": mr["eta_cross_mean"],
                        "tau_min": mr["tau_mean"],
                        "events after dedup": mr["dedup"]["n_after"],
                    },
                ],
                ["resolution", "eta_self", "eta_cross", "tau_min", "events after dedup"],
            )
        )
        add(
            f"\n**Rounding moves eta_self by {p['rounding_bias_eta_self']:+.4f}.** Rounding to "
            f"integer minutes forces the de-duplication rule to collapse every same-minute pair, "
            f"removing {p['extra_events_removed_by_rounding']} more events than the calibrated "
            f"{sr['dedup']['threshold_seconds']:.0f} s rule does, and taking the measured "
            "excitation with them.\n"
        )

    # ---- steps 8 and 9
    for split in ("dev", "holdout"):
        for path in sorted(RESULTS.glob(f"fit_*_{split}.json")):
            man = json.loads(path.read_text())
            p = man["payload"]
            hk = p["headline"]["hawkes"]
            add(f"\n## {'8' if split == 'dev' else '9'}. Fit -- {path.stem}\n")
            add(
                _table(
                    [
                        {"quantity": "eta_self (the momentum estimate)", "value": hk["eta_self"]},
                        {"quantity": "eta_cross", "value": hk["eta_cross"]},
                        {"quantity": "kernel timescale 1/beta (min)", "value": hk["tau_minutes"]},
                        {"quantity": "tau pinned to its box", "value": hk["tau_at_boundary"]},
                        {"quantity": "spectral radius", "value": hk["spectral_radius"]},
                        {"quantity": "detection floor", "value": p.get("detection_floor")},
                        {
                            "quantity": "parametric bootstrap p",
                            "value": p.get("parametric_bootstrap", {}).get("p_value"),
                        },
                    ],
                    ["quantity", "value"],
                )
            )
            j = p.get("across_jitter_draws")
            if j:
                add(
                    f"\nAcross {j['n_draws']} jitter draws: eta_self "
                    f"{j['eta_self_mean']:.4f} +/- {j['eta_self_sd']:.4f} "
                    f"(range {j['eta_self_min']:.4f} to {j['eta_self_max']:.4f}).\n"
                )
            ci = p.get("cluster_bootstrap_ci95")
            if ci:
                add(f"\nCluster bootstrap over whole matches, 95% interval: [{ci[0]:.4f}, {ci[1]:.4f}].\n")
            sens = p.get("sensitivities")
            if sens:
                add("\n### Sensitivities\n")
                rows = [
                    {
                        "variant": k,
                        **{
                            kk: vv
                            for kk, vv in v.items()
                            if kk
                            in ("eta_self", "eta_cross", "tau_minutes", "delta_eta_self", "tau_at_boundary")
                        },
                    }
                    for k, v in sens.items()
                ]
                add(
                    _table(
                        rows,
                        [
                            "variant",
                            "eta_self",
                            "eta_cross",
                            "tau_minutes",
                            "delta_eta_self",
                            "tau_at_boundary",
                        ],
                    )
                )
            if p.get("detection_floor_source"):
                add(f"\nDetection floor read from `{p['detection_floor_source']}`.\n")
            if p.get("verdict"):
                add(f"\n**Verdict.** {p['verdict']}\n")

    # ---- is the timescale even identified
    for path in sorted(RESULTS.glob("tau_profile_*.json")):
        man = json.loads(path.read_text())
        p = man["payload"]
        add(f"\n## A. Is the kernel timescale identified? ({path.stem.replace('tau_profile_', '')})\n")
        add(_table(p["profile"], ["tau_minutes", "eta_self", "eta_cross", "loglik", "delta_loglik_vs_best"]))
        add(
            f"\nLog-likelihood range across the whole band: **{p['loglik_range']:.2f}**. "
            f"eta_self read off at tau = 5 min: {p['eta_at_tau_5']:.4f}.\n"
        )
        add(f"\n> {p['note']}\n")

    # ---- cross-source
    for path in sorted(RESULTS.glob("cross_source_*.json")):
        p = json.loads(path.read_text())["payload"]
        if "error" in p:
            continue
        na, nb = p.get("names", ["understat", "statsbomb"])
        sh, xg, fits = p["shots"], p["xg_totals"], p["fits"]
        add(f"\n## B. {na} against {nb}, same fixtures\n")
        add(f"{p['aligned_fixtures']} fixtures align.\n")
        add(
            _table(
                [
                    {"quantity": "shots", na: sh[na], nb: sh[nb]},
                    {"quantity": "total xG", na: round(xg[na], 1), nb: round(xg[nb], 1)},
                    {"quantity": "eta_self", na: fits[na]["eta_self"], nb: fits[nb]["eta_self"]},
                    {"quantity": "1/beta (min)", na: fits[na]["tau_minutes"], nb: fits[nb]["tau_minutes"]},
                    {
                        "quantity": "shots removed by dedup",
                        na: f"{fits[na]['dedup']['removed_fraction']:.1%}",
                        nb: f"{fits[nb]['dedup']['removed_fraction']:.1%}",
                    },
                ],
                ["quantity", na, nb],
            )
        )
        add(
            f"\nPer-match shot counts correlate at {sh['per_match_correlation']:.3f} and differ by "
            f"{sh['mean_absolute_difference']:.2f} shots per match on average; total xG agrees to "
            f"{abs(xg[na] / xg[nb] - 1):.1%}. The feeds are looking at the same football. "
            "Where they disagree about eta_self, they disagree about the clock.\n"
        )
        byp = p.get("fits_by_provider") or {}
        if byp:
            add("\nThe pooled side, one provider at a time, on the same aligned fixtures:\n")
            add(
                _table(
                    [
                        {
                            "provider": k,
                            "matches": v["matches"],
                            "eta_self": v["eta_self"],
                            "1/beta (min)": v["tau_minutes"],
                            "shots removed": f"{v['dedup']['removed_fraction']:.1%}",
                        }
                        for k, v in byp.items()
                    ],
                    ["provider", "matches", "eta_self", "1/beta (min)", "shots removed"],
                )
            )

    # ---- secondary
    man = _load_one("secondary_*")
    if man:
        p = man["payload"]
        q = p["quality_regression"]
        add("\n## C. Secondary analyses (extensions, not the deliverable)\n")
        add(
            f"**Chance quality.** psi1 = {q['psi1']:.4f} (se {q['psi1_se']:.4f}, t = {q['psi1_t']:.2f}) "
            f"on {q['n']} shots: no evidence that teams create *better* chances while excited, only a "
            "question about whether they create more.\n"
        )
        rows = [
            {"state": k, **{kk: v.get(kk) for kk in ("n_matches", "n_events", "eta_self", "tau_minutes")}}
            for k, v in p["state_dependent_eta"].items()
            if k != "note"
        ]
        add("\n**Self-excitation by score state.**\n")
        add(_table(rows, ["state", "n_matches", "n_events", "eta_self", "tau_minutes"]))
        add(f"\n> {p['state_dependent_eta']['note']}\n")

    add("\n## Reproducing\n")
    add(
        "```\nmake venv && make check\nmake ingest-statsbomb ingest-wyscout build-pooled\nmake pipeline\n```\n"
    )
    add(
        "`make ingest-understat` is the overnight pull and is deliberately not part of "
        "`make pipeline`. Holdout numbers come from `make fit-holdout`, which is run once.\n"
    )
    return "\n".join(out)


def main() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    text = build()
    path = DOCS / "RESULTS.md"
    path.write_text(text)
    print(f"wrote {path} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
